name: test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: start github actions
        run: |
          echo another test Start!
